### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by tvooo** [ThePacielloGroup/inclusive-design-principles#59] opened 2017-06-09 14:10 UTC
I'm happy to contribute to a German translation of the principles, in order to reach a wider German audience.

In this context: right now it seems hard to keep both the HTML/structure as well as the content in sync across multiple locales. What can we do about this?

**Comment by MarcusMorba** [comment] 2023-10-10 11:05
@tvooo, @chaals - the technical challenge is solved, also the content seems translated. @LJWatson committed the code in august 2023: https://github.com/ThePacielloGroup/inclusive-design-principles/commits?author=LJWatson

Now I am wondering if there´s a blocker, which holds back an official release to the website.

@partisiber - could you answer my question?

**Comment by partisiber** [comment] 2023-10-10 12:20
@MarcusMorba I only recived an Email from Léonie Watson that although the PR is merged it can not be published to the live site because of technical difficulites - I do not know the details

**Comment by MarcusMorba** [comment] 2023-10-12 11:00
> @MarcusMorba I only recived an Email from Léonie Watson that although the PR is merged it can not be published to the live site because of technical difficulites - I do not know the details

Thanks for the information. Hope this can be solved soon.

**Comment by LJWatson** [comment] 2023-10-12 17:47
We're working on it. Bear with us though. It's an "evenings and weekends" job for us 😊

**Comment by LJWatson** [comment] 2023-10-29 11:49
@partisiber and @MarcusMorba, we've moved the IDP to a new home and tagged you in an issue there. Just in case you didn't get the ping, the issue is here:
https://github.com/Inclusive-Design-Principles/inclusive-design-principles/issues/7

**Closed by LJWatson** 2023-10-29 11:49 UTC
